# One Hot Encoding
    ->for nominal categorical data set

------
------

In [60]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first' , dtype=np.int32)      
#if we have done this true then we have droped the first column just like we used to do while removing the multilinearity
# there is also a parameter known as sparse which when we do false then it will dont make the fit_transformation sparse matrix
#after doing that  change in sparse the output will be numpy array and we can remove the toarray() function

In [61]:
df = pd.read_csv(r"D:/ML/DataSet/cars.csv")

In [62]:
df.sample(3)

       brand  km_driven    fuel         owner  selling_price
5936   Honda      30000  Petrol   First Owner         780000
3938    Jeep      15000  Diesel   First Owner        1515000
5746  Maruti      60000  Petrol  Second Owner          45000

In [63]:
df['fuel'].unique()

<StringArray>
['Diesel', 'Petrol', 'LPG', 'CNG']
Length: 4, dtype: str

In [64]:
df.shape

(8128, 5)

In [65]:
df['brand'].nunique()

32

------
------

## OneHot Encoding using Pandas

pandas library itself have a function called get_dummies(data frame name, columns=['column name which is to be encoded'])

this is the direct method to deal with ohe in pandas library itself

In [66]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)     #we are currently avoiding brand 
# which should be here as we dont wanted 32 extra columns and how much will it increase in relative , we dont know.

#also, we have added dtype = int as the pd is giving me false instead of 0. 
# SO, THIS WILL CHANGE THE DATATYPE OF THE REQUIRED COLUMNS TO INT INSTEAD OF BOOL

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

## K-1 encoding

In [67]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)

#this will solve the problem of the multi-linearity

#first category of each column from which we have derived the category , the column of the 1st category is removed!

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

but we generally dont uses the pandas method

------
--------

For ML we don't use the pandas as it doesn't remember where it have kept the columns, basically their positions.

Hence, we use sklearn's module for this job

## OneHot Encoding using sklearn

In [68]:
#we have in the starting imported the important libraries and modules as a guess

X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:4],df.iloc[:,:-1],test_size=0.2,random_state=0)

In [69]:
# from sklearn.preprocessing import OneHotEncoder   #this  is already imported in the starting , just writting to inform that it is used here. 
# ohe = OneHotEncoder()

now , we have to do a unique work, we have to apply one hot encoding to only 2 columns fuel and owner not on brand or km_driven as one will make work slow and other is numerical.

the only option we have is to first take the 2 columns out , then apply the encoding and then remerge them, and then we get our complete input.

since, it is so hectic and difficult, one way to deal is  column transformation which we will study in next lecture!

In [70]:
ohe.fit_transform(X_train[['fuel','owner']])            #by default ohe store the values in sparks matrix

#since we have to apply the required transformation on only 2 so we have done it by passing a list in X_train and in that again
# we have passed a list of the required columns

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 8735 stored elements and shape (6502, 7)>

In [71]:
# if we have to see them we have to write .toarray() function

ohe.fit_transform(X_train[['fuel','owner']]).toarray()

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [72]:
X_train_new  = ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new  = ohe.transform(X_test[['fuel','owner']]).toarray()         #since we dont train on test so, we dont have written fit

now we have to append the 2 columns which are not transformed with these 2

In [73]:
X_train[['brand','km_driven']].values       #this .values will convert this into a numpy array

array([['Hyundai', 60000],
       ['Tata', 150000],
       ['Hyundai', 110000],
       ...,
       ['Hyundai', 90000],
       ['Volkswagen', 90000],
       ['Hyundai', 110000]], shape=(6502, 2), dtype=object)

now , for now only lets assume that we have the 1st 2 transformation done and we are looking for their stacking/ appending

In [74]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))      #we have passed a tuple over here!|

array([['Hyundai', 60000, 0, ..., 0, 0, 0],
       ['Tata', 150000, 1, ..., 0, 0, 1],
       ['Hyundai', 110000, 1, ..., 1, 0, 0],
       ...,
       ['Hyundai', 90000, 0, ..., 1, 0, 0],
       ['Volkswagen', 90000, 1, ..., 0, 0, 0],
       ['Hyundai', 110000, 0, ..., 0, 0, 0]],
      shape=(6502, 9), dtype=object)

## OneHot Encoding with Top Categories

what we do under this topic is that we encode the column having many categories

In [75]:
counts = df['brand'].value_counts()

In [76]:
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [77]:
df['brand'].nunique()

32

In [78]:
threshold = 100

In [83]:
mask = counts<=threshold
print(mask)

brand
Maruti           False
Hyundai          False
Mahindra         False
Tata             False
Toyota           False
Honda            False
Ford             False
Chevrolet        False
Renault          False
Volkswagen       False
BMW              False
Skoda            False
Nissan            True
Jaguar            True
Volvo             True
Datsun            True
Mercedes-Benz     True
Fiat              True
Audi              True
Lexus             True
Jeep              True
Mitsubishi        True
Land              True
Force             True
Isuzu             True
Kia               True
Ambassador        True
MG                True
Daewoo            True
Ashok             True
Opel              True
Peugeot           True
Name: count, dtype: bool

In [86]:
counts[mask]

brand
Nissan           81
Jaguar           71
Volvo            67
Datsun           65
Mercedes-Benz    54
Fiat             47
Audi             40
Lexus            34
Jeep             31
Mitsubishi       14
Land              6
Force             6
Isuzu             5
Kia               4
Ambassador        4
MG                3
Daewoo            3
Ashok             1
Opel              1
Peugeot           1
Name: count, dtype: int64

In [88]:
replace = counts[mask].index

In [101]:
pd.get_dummies(df['brand'].replace(replace,'uncommon'),dtype=int).sample(5)

#learn the way to do this to replace the unwanted part under a common name

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2505,0,0,0,0,0,0,1,0,0,0,0,0,0
2657,0,0,0,0,0,0,0,0,0,0,1,0,0
4393,0,0,0,0,0,0,0,0,0,0,0,0,1
1774,0,0,0,1,0,0,0,0,0,0,0,0,0
5233,0,0,0,0,1,0,0,0,0,0,0,0,0

-----------------------
-----------------------

# END  of  Day-27